In [2]:
import numpy as np

In [3]:
np

<module 'numpy' from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/numpy/__init__.py'>

# Creating Arrays

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [7]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 12])
a

array([ 1,  2,  3,  4,  5,  6,  7, 12])

In [9]:
a[2]

3

In [11]:
a[2] = 10
a

array([ 1,  2, 10,  4,  5,  6,  7, 12])

In [12]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [15]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

# Multi-dementional Arrays

In [5]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [14]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
n

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
n[0, 1]

2

In [13]:
n[0] # get row

array([1, 2, 3])

In [15]:
n[:, 1] # get the column 

array([2, 5])

In [16]:
np.random.rand(5, 2)

array([[0.95514773, 0.81342999],
       [0.15737814, 0.36173505],
       [0.69962595, 0.13170824],
       [0.6856192 , 0.32528937],
       [0.92241203, 0.14191837]])

In [17]:
100 * np.random.rand(5, 2)

array([[69.62975726, 57.06182033],
       [33.600277  , 59.71755712],
       [47.41148333, 12.8462664 ],
       [71.65220833, 51.44671897],
       [11.64950715, 76.26866542]])

In [19]:
np.random.randint(low=0, high=100, size=(5, 2))

array([[54, 37],
       [89, 28],
       [42, 90],
       [ 0, 63],
       [58, 55]])

# Element-wise operations

In [20]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [21]:
a + 1

array([1, 2, 3, 4, 5])

In [22]:
a * 2

array([0, 2, 4, 6, 8])

In [23]:
a / 100

array([0.  , 0.01, 0.02, 0.03, 0.04])

# Comparison Operations

In [24]:
a

array([0, 1, 2, 3, 4])

In [25]:
a >= 2

array([False, False,  True,  True,  True])

In [31]:
b = np.array([5, 4, 3, 2, 1])
b

array([5, 4, 3, 2, 1])

In [32]:
a > b

array([False, False, False,  True,  True])

In [33]:
a[a>b] # which elements are True?

array([3, 4])

# Summarizing Operations

In [34]:
a

array([0, 1, 2, 3, 4])

In [35]:
a.max()

4

In [36]:
a.sum()

10

In [37]:
a.mean()

2.0

In [38]:
a.std()

1.4142135623730951

In [39]:
a.min()

0