In [1]:
import numpy as np

In [2]:
# .shape: show dimension and tuple of ndarray
# .ndim: dimension of ndarray

array1 = np.array([1, 2, 3])
array1.shape, type(array1), array1.ndim

((3,), numpy.ndarray, 1)

In [3]:
# Data of an ndarray are in same type
# If converting a list including various data types into ndarray,
# the types of data in original list are changed to the biggest type of that list
list2 = [1, 2, 't']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 't'] <U21
[1. 2. 3.] float64


In [4]:
# arange, zeros, ones
# create ndarray conveniently
seq_arr = np.arange(10)
seq_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
zero_arr = np.zeros((2, 2), dtype='int32') # default type is float64
zero_arr

array([[0, 0],
       [0, 0]], dtype=int32)

In [6]:
# reshape: change dimensio and size
arr1 = np.arange(10)
arr2 = arr1.reshape(2, 5)
print(arr1, arr2)

# -1을 인자로 사용하면 원래 ndarray와 호환되는 새로운 shape로 변환해줌
arr3 = np.arange(12)
arr4 = arr3.reshape(-1, 4)
print(arr3, arr4)

[0 1 2 3 4 5 6 7 8 9] [[0 1 2 3 4]
 [5 6 7 8 9]]
[ 0  1  2  3  4  5  6  7  8  9 10 11] [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [9]:
# indexing
array = np.arange(start=1, stop=10)
value = array[2]
print(array)
print(type(array))
print(value)
print(type(value))

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
3
<class 'numpy.int64'>


In [10]:
array1d = np.arange(1, 10)
array2d = array1d.reshape(3, 3)
print(array2d)

print("Value of row=0 col=0 ", array2d[0,0])
print("Value of row=0 col=1 ", array2d[0,1])
print("Value of row=1 col=0 ", array2d[1,0])
print("Value of row=2 col=2 ", array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Value of row=0 col=0  1
Value of row=0 col=1  2
Value of row=1 col=0  4
Value of row=2 col=2  9


In [11]:
array = np.arange(start=1, stop=10)
array4 = array1[:3]
print(array4, type(array4))

array5 = array[3:]
print(array5, type(array5))

array6 = array[:]
print(array6, type(array6))

[1 2 3] <class 'numpy.ndarray'>
[4 5 6 7 8 9] <class 'numpy.ndarray'>
[1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>


In [13]:
array1d = np.arange(1, 10)
array2d = array1d.reshape(3, 3)
print(array2d)

print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
print('array2d[1:3, :] \n', array2d[1:3, :])
print('array2d[:,:] \n', array2d[:,:])
print('array2d[:2,1] \n', array2d[:2,1])
print('array2d[:2,0] \n', array2d[:2,0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:,:] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2,1] 
 [2 5]
array2d[:2,0] 
 [1 4]


In [14]:
# Fancy Indexing
array1d = np.arange(1, 10)
array2d = array1d.reshape(3, 3)
print(array2d)

array3 = array2d[[0, 1], 2]
print(array3)
array4 = array2d[[0, 1], 0:2]
print(array4)
array5 = array2d[[0, 1]]
print(array5)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[3 6]
[[1 2]
 [4 5]]
[[1 2 3]
 [4 5 6]]


In [16]:
# Boolean Indexing
array1d = np.arange(1, 10)
print(array1d > 5)
print(array1d[array1d > 5])

[False False False False False  True  True  True  True]
[6 7 8 9]


In [17]:
# sort
arg_array = np.array([3, 1, 9, 5])
print(arg_array)

# np.sort
sort_array1 = np.sort(arg_array)
print(sort_array1)

# ndarray.sort
sort_array2 = arg_array.sort()
print(arg_array)
print(sort_array2)

[3 1 9 5]
[1 3 5 9]
[1 3 5 9]
None


In [18]:
array2d = np.array([[8, 12], [7, 1]])

sort_2d_axis0 = np.sort(array2d, axis=0)
print(sort_2d_axis0)
sort_2d_axis1 = np.sort(array2d, axis=1)
print(sort_2d_axis1)

[[ 7  1]
 [ 8 12]]
[[ 8 12]
 [ 1  7]]


In [21]:
# argsort
org_arr = np.array([3, 1, 9, 5])
sort_indices = np.argsort(org_arr)
print(sort_indices)

# desc order
sort_indices_desc = np.argsort(org_arr)[::-1]
print(sort_indices_desc)

# practical Example
name_arr = np.array(['Eudite', 'Samuel', 'Ivor', 'Reticia'])
score_arr = np.array([90, 56, 87, 83])
sort_idc_asc = np.argsort(score_arr)
sort_idc_desc = np.argsort(score_arr)[::-1]

print(sort_idc_asc)
print(name_arr[sort_idc_asc])
print(sort_idc_desc)
print(name_arr[sort_idc_desc])

[1 0 3 2]
[2 3 0 1]
[1 3 2 0]
['Samuel' 'Reticia' 'Ivor' 'Eudite']
[0 2 3 1]
['Eudite' 'Ivor' 'Reticia' 'Samuel']


In [23]:
# 내적
arr_a = np.arange(1, 7).reshape([2, 3])
arr_b = np.arange(7, 13).reshape([3, 2])
dot_product = np.dot(arr_a, arr_b)
print(arr_a)
print(arr_b)
print(dot_product)

[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]
[[ 58  64]
 [139 154]]


In [24]:
# Transpose
arr = np.arange(1, 5).reshape([2, 2])
arr_transpose = np.transpose(arr)
print(arr)
print(arr_transpose)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
