In [3]:
# K fold 교차 검증
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
import numpy as np

iris = load_iris()
features = iris.data
label = iris.target
dt_clf = DecisionTreeClassifier(random_state=156)

# 5개의 폴드 세트로 분리하는 KFold 객체와 폴드 세트별 정확도를 담을 리스트 객체 생성
kfold = KFold(n_splits=5)
cv_accuracy = []
print(f'붓꽃 데이터 세트 크기: {features.shape[0]}')

붓꽃 데이터 세트 크기: 150


In [5]:
n_iter = 0
# KFold 객체의 split()을 호출하면 폴드 별 학습용, 검증용 테스트의 로우 인덱스를 array로 반환
for train_index, test_index, in kfold.split(features):
    X_train, X_test = features[train_index], features[test_index]
    y_train, y_test = label[train_index], label[test_index]

    # 학습 및 예측
    dt_clf.fit(X_train, y_train)
    pred = dt_clf.predict(X_test)
    n_iter += 1

    # 반복시마다 정확도 측정
    accuracy = np.round(accuracy_score(y_test, pred))
    train_size = X_train.shape[0]
    test_size = X_test.shape[0]
    print(f"{n_iter} 교차 검증 정확도: {accuracy}, 학습 데이터 크기: {train_size}, 검증 데이터 크기: {test_size}")
    print(f"{n_iter} 검증 세트 인덱스: {test_index}")
    cv_accuracy.append(accuracy)

# 개별 iteration별 정확도를 합하여 평균 정확도 계산
print(f"평균 검증 정확도: {np.mean(cv_accuracy)}")

1 교차 검증 정확도: 1.0, 학습 데이터 크기: 120, 검증 데이터 크기: 30
1 검증 세트 인덱스: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
2 교차 검증 정확도: 1.0, 학습 데이터 크기: 120, 검증 데이터 크기: 30
2 검증 세트 인덱스: [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]
3 교차 검증 정확도: 1.0, 학습 데이터 크기: 120, 검증 데이터 크기: 30
3 검증 세트 인덱스: [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89]
4 교차 검증 정확도: 1.0, 학습 데이터 크기: 120, 검증 데이터 크기: 30
4 검증 세트 인덱스: [ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]
5 교차 검증 정확도: 1.0, 학습 데이터 크기: 120, 검증 데이터 크기: 30
5 검증 세트 인덱스: [120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]
평균 검증 정확도: 1.0


In [6]:
# Stratified K Fold 
# .split() 에서 skf.split(iris_df, iris_df['label'])

from sklearn.model_selection import StratifiedKFold

dt_clf = DecisionTreeClassifier(random_state=156)

skfold = StratifiedKFold(n_splits=3)
n_iter = 0
cv_accuracy = []

for train_index, test_index in skfold.split(features, label):
    X_train, X_test = features[train_index], features[test_index]
    y_train, y_test = label[train_index], label[test_index]

    # 학습 및 예측
    dt_clf.fit(X_train, y_train)
    pred = dt_clf.predict(X_test)
    n_iter += 1

    # 반복시마다 정확도 측정
    accuracy = np.round(accuracy_score(y_test, pred), 4)
    train_size = X_train.shape[0]
    test_size = X_test.shape[0]
    print(f"{n_iter} 교차 검증 정확도: {accuracy}, 학습 데이터 크기: {train_size}, 검증 데이터 크기: {test_size}")
    print(f"{n_iter} 검증 세트 인덱스: {test_index}")
    cv_accuracy.append(accuracy)

# 개별 iteration별 정확도를 합하여 평균 정확도 계산
print(f"교차 검증별 정확도: {np.round(cv_accuracy, 4)}")
print(f"평균 검증 정확도: {np.mean(cv_accuracy)}")

1 교차 검증 정확도: 0.98, 학습 데이터 크기: 100, 검증 데이터 크기: 50
1 검증 세트 인덱스: [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  50
  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115]
2 교차 검증 정확도: 0.94, 학습 데이터 크기: 100, 검증 데이터 크기: 50
2 검증 세트 인덱스: [ 17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82 116 117 118
 119 120 121 122 123 124 125 126 127 128 129 130 131 132]
3 교차 검증 정확도: 0.98, 학습 데이터 크기: 100, 검증 데이터 크기: 50
3 검증 세트 인덱스: [ 34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  83  84
  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149]
교차 검증별 정확도: [0.98 0.94 0.98]
평균 검증 정확도: 0.9666666666666667


In [9]:
# label encoding
from sklearn.preprocessing import LabelEncoder

items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '믹서', '선풍기']
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print(f"인코딩 변환값 : {labels}")

# decoding
print(encoder.inverse_transform(labels))

인코딩 변환값 : [0 1 4 5 3 2 3]
['TV' '냉장고' '전자레인지' '컴퓨터' '선풍기' '믹서' '선풍기']


In [11]:
# One-hot Encoder
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '믹서', '선풍기']
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
labels = labels.reshape(-1, 1)

onehot_encoder = OneHotEncoder()
onehot_encoder.fit(labels)
onehot_labels = onehot_encoder.transform(labels)
print(f"원핫 인코딩 데이터: {onehot_labels.toarray()}")

# 판다스 - get_dummies
import pandas as pd

df = pd.DataFrame({'items': items})
pd.get_dummies(df)

원핫 인코딩 데이터: [[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]]


items_TV  items_냉장고  items_믹서  items_선풍기  items_전자레인지  items_컴퓨터
0      True      False     False      False        False      False
1     False       True     False      False        False      False
2     False      False     False      False         True      False
3     False      False     False      False        False       True
4     False      False     False       True        False      False
5     False      False      True      False        False      False
6     False      False     False       True        False      False

In [14]:
# 정규화
iris = load_iris()
iris_df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
print(f"평균 값: {iris_df.mean()}")
print(f"분산 값: {iris_df.var()}")

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
# scaler로 데이터셋 변환 후 fit, transform 호출
scaler.fit(iris_df)
iris_scaled: np.ndarray = scaler.transform(iris_df) 

# transform시 스케일 변환된 데이터셋 -> numpy ndarray -> DataFrame
iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)
print(f"평균 값: {iris_df_scaled.mean()}")
print(f"분산 값: {iris_df_scaled.var()}")

# 모든 컬럼 값의 평균이 0에 가까운 값, 그리고 분산은 1에 가까운 값으로 변환됨을 알 수 있다.

평균 값: sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64
분산 값: sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64
평균 값: sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64
분산 값: sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


In [15]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)
print(f"평균 값: {iris_df_scaled.mean()}")
print(f"분산 값: {iris_df_scaled.var()}")

평균 값: sepal length (cm)    0.428704
sepal width (cm)     0.440556
petal length (cm)    0.467458
petal width (cm)     0.458056
dtype: float64
분산 값: sepal length (cm)    0.052908
sepal width (cm)     0.032983
petal length (cm)    0.089522
petal width (cm)     0.100869
dtype: float64


In [16]:
# Scaler
train_array = np.arange(0, 11).reshape(-1, 1)
test_array = np.arange(0, 6).reshape(-1, 1)

scaler = MinMaxScaler()
scaler.fit(train_array)
train_scaled = scaler.transform(train_array)
print(f"원본 train array 데이터: {np.round(train_array.reshape(-1), 2)}")
print(f"scaled된 train array 데이터: {np.round(train_scaled.reshape(-1), 2)}")

test_scaled = scaler.transform(test_array)
print(f"원본 test array 데이터: {np.round(test_array.reshape(-1), 2)}")
print(f"scaled된 test array 데이터: {np.round(test_scaled.reshape(-1), 2)}")

원본 train array 데이터: [ 0  1  2  3  4  5  6  7  8  9 10]
scaled된 train array 데이터: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
원본 test array 데이터: [0 1 2 3 4 5]
scaled된 test array 데이터: [0.  0.1 0.2 0.3 0.4 0.5]
